version: '3'
services:
    web:
        build:
            context: .
            dockerfile: docker/Dockerfile_python
        working_dir: /app
        # environment:
            # - DJANGO_SETTINGS_MODULE=mylogistic.settings.local_docker
        command: bash -c "uvicorn main:app --reload --port 8001 --host 0.0.0.0"
        volumes:
            - ./app:/app
        ports:
            - 8001:8001
